package com.geneticplanner.domain.validation

enum class ValidationErrorCode {
    DUPLICATE_ID,
    INVALID_PLANNING_HORIZON,
    INVALID_TIME_SLOT,
    UNKNOWN_RESOURCE_TYPE,
    UNKNOWN_CANDIDATE_RESOURCE,
    CANDIDATE_RESOURCE_TYPE_MISMATCH,
    INVALID_REQUIREMENT_QUANTITY,
    INSUFFICIENT_CANDIDATE_RESOURCES,
    UNKNOWN_TIME_SLOT,
    UNKNOWN_LOCATION,
    NO_POSSIBLE_TIME_SLOT
}